version: "2"
services:
  postgres:
        container_name: postgres
        image: postgres:9.6
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=demospotify
        expose:
          - 5432
  back:
        container_name: backend
        image: maven:3.6.0-jdk-8-alpine
        links:
          - postgres
        ports:
          - 8080:8080
        volumes:
          - ./demospotify:/demospotify
        working_dir: /demospotify
        command: "mvn spring-boot:run"
  front:
        container_name: front
        image: node:8.12.0-alpine
        links:
          - back
        ports:
          - 8081:8081
        volumes:
          - ./demospotify_front:/demospotify
        working_dir: /demospotify
        command: "./start.sh"
